- docs/images.coffee.md
I noticed that pdfkit supports passing a data uri with base64 encoded data in addition to the image path when adding an image but this was not documented.
> Updated Docs to list support for a base64 data uri and buffer when adding an image

- lib/font/tables/name.coffee
- lib/font/ttf.coffee
- lib/image/jpeg.coffee
> Fixed regression caused by CoffeeScript 1.9.0+

- lib/object.coffee
I have been working on a "optional" loaded javascript file that will import a pdf into a new pdf for output.   Everything works other than pdfkit currently doesn't support outputting a "hex" value.   i.e \< 0A \>, the Object.convert wants to either treat it as a String key i.e. /0A   or as a Object \<\< 0A \>\>
> Fix missing object.coffee outputs.

- lib/image/png.coffee
Now fontkit branch should be functional. Without this patch you will have following:
```
ReferenceError: document is not defined
at PNGImage.embed (/Users/ilovriakov/side/pdfkit/js/image/png.js:25:18)
at PDFDocument.module.exports.image (/Users/ilovriakov/side/pdfkit/js/mixins/images.js:29:15)
at Object.<anonymous> (/Users/ilovriakov/side/pdfkit/demo/test.coffee:22:5)
at Object.<anonymous> (/Users/ilovriakov/side/pdfkit/demo/test.coffee:1:1)
at Module._compile (module.js:460:26)
```
> Fixing typo which make tests fail

- lib/path.coffee
Fixed an issue which causes SVG path to fail when parsing an Arc.
When drawing SVG arcs, due to rounding errors in the Beizer Curve calculation, some of the outputs (x1,y1,x2,y2,x3,y3)  were within 1E-16 of an integer which cause the drawing of the Beizer curve to fail. By checking the precision and rounding to nearest integer the problem is fixed.
This also closes out issue #288.
The following path posted by StephanVD renders (example attached).
> M 100,100 L 100,0 A 100,100 0 0 1 175.44817868315766,165.6320983467258 Z
The following path posted by jaisor rendors with some minor amendments to fix the rounding errors in the source (example attached).
> M6.429183357567481e-15,-105A105,105 0 0,1 104.77516788447983,-6.867619294855041L74.83940563177131,-4.905442353467887A75,75 0 0,0 …
> Path.coffee updated to fix SVG Path Arcs

- lib/mixins/vector.coffee
I accidentally destroyed my previous pull request so I make a new one
Fixes:
- Use cubic instead of distorted quadratic curves, by @bjnsn
- Gap showing in Chrome built-in PDF viewer due to missing closePath() call
- Problem if corner radius > 1/2 * rectangle dimension
Screnshot of PDF showing the diffrences
> Rounded rect

- docs/getting_started.coffee.md
I couldn't find a doc with page sizes, so I'm just linking to the code.
I submitted this to the gh-pages branch instead of master in https://github.com/devongovett/pdfkit/pull/567.
📄
> Fix paper sizes link

- lib/mixins/text.coffee
this change will allow users to set the size of the circle on bullet list item in the options via the setting "bulletRadius"
usage: 
```
doc.list(["item1", "item2", "item3"], x, y, { bulletRadius: 2 });
```
without setting bulletRadius, it will default to the size as it was before.
> allow setting size of list bullet circle via options

- lib/line_wrapper.coffee
fix #345
The problem was the function emitLine() being called twice if the last line contained only one word, at lines 158 and 178.
There can be some side-effects because I don't understand completely how the code works!
> Line wrapper bug

- lib/mixins/vector.coffee
The PDF reference allows complex dash patterns. The 1st argument of the `dash` function can now be an array.
> Add support for dash array

- lib/gradient.coffee
- lib/mixins/color.coffee
When there is opacity ≠ 1 specified, the gradient is drawn and masked on a `Tiling Pattern`. The tiling has `BBox`, `XStep` & `YStep` values equal to the dimensions of the page, to avoid any clipping or tiling repetition. `Patterns` are unaffected by the document's "Current Transformation Matrix" so the clipping rectangle is always aligned with the page borders (`SMasks` and `Groups` don't have this property). Problems could possibly happen if a gradient is embedded on multiple pages (this doesn't work anyway) of different sizes.
This pull request resolves the following issues:
- Fix use of opacity gradients with `fillAndStroke` (fix #214)
- Fix the reuse of the same gradient after transformations
- Fix the wrong clipping of some gradients with opacity (#587-2nd commit)
- Add `transform` …
> Fix issues with opacity gradients

- docs/text.coffee.md
Hello,
I'd like to provide some enhancement on the Documentation. This is about the pdfkit standard Fonts and where to find the Labels, an issue I found myself struggling with some days ago. It's quite a helpful addition for every newbie (like me).
> Enhanced Doc for standard Fonts

- lib/mixins/text.coffee
writing `undefined` or `null` to a document is hardly the user's intention, so this fixes it
> print empty string instead of undefined or null

- lib/mixins/vector.coffee
The function wasn't working in these cases:
`scale(xFactor, yFactor)`
`scale(xyFactor, options)`
Fix #598
> Fix scale function

- lib/object.coffee
When using UTF-16 for encoding strings, specail characters should be escaped directly in UTF-16 encoded string. Pdf format doesn't expect escape by 2 bytes characters.
Code example:
```javascript
var PdfDoc = require("pdfkit");
var fs = require("fs");
var pdf = new PdfDoc({
size: "A4",
margin: 14
});
pdf.info["Title"] = "Test title (ä)";
pdf.pipe(fs.createWriteStream("test.pdf"));
pdf.end();
```
Current version of code will create next metadata: `/Title (юя T e s t   t i t l e   \ ( д \ ))`
This is ` \ (` not escaped bracket will broke pdf info.
Metadata should be like this: `/Title (юя T e s t   t i t l e   \( д \))`
So I propose to change order of encoding and escaping.
> Fix incorrect escape of special characters when using UTF-16

- lib/mixins/vector.coffee
Adds `arc()` vector method. Uses same signature as [HTML5 Canvas arc](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc).
> Add arc() drawing method

- docs/vector.coffee.md
Update the documentation for `rotate()` (fix #657)
Add how to "unclip"
> rotate origin - unclip

- lib/mixins/annotations.coffee
- lib/mixins/text.coffee
```
doc.link(x, y, width, height, pageNumber)
doc.text(text, x, y, {link: pageNumber})
```
Fix #700 fix #467
> Add support for link to another page

- lib/line_wrapper.coffee
while w > @spaceLeft
w = @wordWidth word.slice(0, --l) 
runs endless, if space is to tight for even a single character. Changed it to:
while w > @spaceLeft and l > 0
w = @wordWidth word.slice(0, --l)
> Fixed line_wrapper.coffee: potential endless loop

- lib/line_wrapper.coffee
If linewidth in linewrapper is too small even for just ellipsis, the while-loop starts and never ends
Do while-loop till buffer is not empty string. After while-loop check if there is enough space to contain buffer and ellipsis, and only if this condition is true, add ellipsis to buffer
> Fix linewrapper ellipsis inifinite loop

- lib/line_wrapper.coffee
This is a speed enhancement to the word wrapping algorithm.  In the case of massive words, such as in the case of a huge number of spaces, this reduces the time from effectively infinite to near-instant.  In short, we make an educated guess as to how much space we have so that we start very close to the correct slice of the word, then we tweak as necessary by shrinking or growing our slice range.
Thanks to @mgetz for getting the core changes in place!
> Long running loop fix

- lib/line_wrapper.coffee
This causes \n characters to be displayed more consistently by passing on required breaks when they are needed.  Before this change, text in the form of "alpha\nbeta\ngamma" could be translated incorrectly in some instances, in the form of:
"alphabeta
gamma"
The expected output, which this change brings about, is:
"alpha
beta
gamma"
> Fix bug with \n translation

- lib/reference.js
This call is not necessary at all. The only consequence of it is that the Pages object will be written after other references, but makes no difference because how PDF object lookup works (using a table ref in the end of file)
On the other size will benefit performance of large documents
> Remove setTimeout call in PDFReference.finalize

- lib/page.js
This saves memory per PDFPage instance. Also less, better compressible, code.
> Use property getter to define PDFPage lazy dictionaries

- lib/security.js
Bugfix for allow enable print document by `printing` property. Because is used wrong number mask to allow print.
Is not possible enable printing with access privileges.
Is possible enable printing.
**Checklist**:
> Bugfix printing privilege

- lib/object.js
- tests/unit/object.spec.js
It uses valueOf when converting String objects
Fixes #923 
**Checklist**:
> Use valueOf when converting String object values

- docs/getting_started.md
- lib/document.js
- lib/mixins/fonts.js
- tests/unit/document.spec.js
Add option to defined default font
default font is always Helvetica 
**Checklist**:
> Add option to defined default font

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- docs/getting_started.md
Doc update, add changelog
**Checklist**:
> Add changelog and improve Get Started document

- lib/font/embedded.js
- tests/unit/font.spec.js
Add fontCache option
#932 
The font layout is always cached
If fontCache option is passed to document as false, the layout is not cached
**Checklist**:
Pending: a better name? 
Edit: renamed to fontLayoutCache since is a technically more correct and to not confound with the font instance cache
> Add fontLayoutCache option

- lib/data.js
- lib/font/afm.js
- lib/font/embedded.js
- lib/gradient.js
- lib/mixins/text.js
- lib/mixins/vector.js
- lib/outline.js
- lib/path.js
Code cleanup
No changes
**Checklist**:
> Cleanup remaining artifacts from CoffeScript conversion

- CHANGELOG.md
- lib/document.js
Bug fix
Links to page numbers do not trigger navigation when clicked.
**Checklist**:
**Code Sample**
```
"use strict";
var fs = require('fs');
var PDFDocument = require('./js/pdfkit');
var doc = new PDFDocument({bufferPages: true});
doc.text("First Page");
doc.addPage();
doc.text('Go To First Page', {link: 0});
doc.end();
doc.pipe(fs.createWriteStream('/tmp/result.pdf'));
```
**Low Level Details**
Without this fix, the link annotation generates a command like this:
```
/S /GoTo
/D [<362030205220> /XYZ null null null]
```
With the fix, the link annotation correctly generates a PDF comand like this:
```
/S /GoTo
/D [6 0 R /XYZ null null null]
```
This comes from the …
> Fix links to page numbers within the document

- docs/annotations.md
- docs/destinations.md
- docs/getting_started.md
- docs/images.md
- docs/text.md
- lib/document.js
- lib/mixins/annotations.js
- lib/mixins/images.js
- lib/mixins/text.js
- lib/name_tree.js
- lib/object.js
- tests/unit/trailer.spec.js
Add support for named destinations.
This is rewrited PR https://github.com/foliojs/pdfkit/pull/720 to ES6 and fixed destinations for images.
Does not allow named destinations.
This basically allows you to link to things before they are defined - so you could create a ToC based on some defined heading names, instead of page numbers (which may change as the document evolves).
All usages and example is in https://github.com/foliojs/pdfkit/pull/720.
**Checklist**:
> Support for named destinations (ES6)

- tests/unit/annotations.spec.js
Fix a test failling due to a object index shift
> Fix object index in annotation test

- README.md
This PR will update README file a bit.
Current code examples shown in readme file do not call the function constructor of PDFDocument.
I've just changed `new PDFDocument` to `new PDFDocument()`.
**What is the current behavior?** N/A
**What is the new behavior?** N/A
**Checklist**:
> Changed new PDFDocument to new PDFDocument().

- README.md
Previous code for throwing error if copy and then pasted. 
So I have included "fs" module as well in the example code.
This PR is about docs update
If someone copy and pastes the example code, it throws an error as "fs" is not defined.
Now, there is no error like "fs" is not defined.  User just need to change the font and image paths in the example code.
**Checklist**:
> Added fs module in example code

- CHANGELOG.md
- package.json
Update version with the following changes:
- Fix setting printing permission
- Fix corruption of string objects in browser
- Add option to set default font
- Remove call to fontkit.openSync
- Add standalone virtual file system implementation
- Add option (fontLayoutCache) to disable font layout cache
@devongovett can you take a look at it and publish?
> Update version to 0.9.1

- CHANGELOG.md
- docs/vector.md
- lib/mixins/vector.js
- tests/unit/document.spec.js
- tests/unit/vector.spec.js
**The dash(...) function now throws errors when passed invalid values**
Fixes #949. Current behavior is that `dash(...)` accepts values such as `0` for length, which breaks rendering in some viewers. There is a demo in the linked issue of the impact of the problem.
**Checklist**:
> throw errors when invalid values passed to dash(...)

- lib/security.js
- tests/unit/document.spec.js
A bug fix.
The following document definition results in `TypeError("Cannot read property 'toString' of undefined"))`:
new PDFDocument({
info: {
Title: undefined,
},
});
This fix will replace `<var>.toString()` with `String(<var>)`, which handles undefined and null gracefully.
**Checklist**:
> Fix bug with undefined / null document properties crashing `new PDFDocument`

- lib/font/embedded.js
I'm using PDFKit to make PDF/A - 3B documents. Thanks to PDFKit's API it's not too difficult to do, but I've come across a minor issue which cannot be solved via the API.
CIDToGIDMap is an optional property of Type 2 CIDFonts with a default value of "Identity"<sup>1</sup>. However, the property is required by the PDF/A specification<sup>2</sup>. Defining this property does not change the behaviour of PDF 1.3 to 1.7 documents but does allow PDFKit to be used to generate valid PDF/A files.
1. PDF 1.7 specification §9.7.4.1
2. [ISO 19005-3 clause 6.2.11.3 test 2](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Parts-2-and-3-rules#rule-62113-2)
CIDToGIDMap property is not set so viewers will …
> Explicitly define default value for CIDToGIDMap

- lib/mixins/annotations.js
The PDF/A specification requires that the annotation flag for links be set to "print". In other words a document must look the same whether it's viewed on screen or printed. This change sets the annotation flag of links to print by default allowing PDFKit's helper methods, such as the one below, to be used to create valid PDF/A documents. Since links are invisible rectangles, setting this flag does not actually affect the appearance of printed documents.
```
doc.text('PDF/A compatible link', 20, 0, { link: 'http://example.com/' });
```
References:
- PDF 1.7 specification §12.5.3
- [PDF/A-2 and PDF/A-3 validation rule 6.3.2-1](https://docs.verapdf.org/validation/pdfa-parts-2-and-3/#rule-632-1)
- [PDF/A-2 and PDF/A-3 validation rule …
> Set link annotation flag to print by default

- CHANGELOG.md
- lib/line_wrapper.js
- tests/unit/text.spec.js
This is a draft for a fix to issue #1018.
For now, a change to line_wrapper.
When a character exceed the width of a empty line, the line wrapper keep adding new line in an infinite loop
The line wrapper catch this case, and allow the character to overflow the line.
**Checklist**:
I would like feedback on this change.
As I understand it, my check only works on empty lines, preventing change with continued text and words at the end of line with content.
Also, the way to handle this case is up for debate. Here are the different ways I tough of handling this :
- Force the insertion of the character, overflowing the width (current behavior)
- Ignore the character, losing part of the …
> Fix infinite loop when lineWidth is smaller than width of a character

- CHANGELOG.md
- README.md
- package.json
Set package version to 0.11 and update docs accordingly
**Checklist**:
Will let @devongovett merge and upload a new npm release
> Update version to 0.11

- lib/document.js
Exposes The `LineWrapper` class on the `PDFDocument` class as `PDFDocument.LineWrapper`
This is so that the data driven reporting system, fluentReports, can match the line breaking of PDFKit for calculating the layout of reports.    I have finally upgraded the fluentReports engine to support the latest PDFKit and the LineWrapper used to be a separate JS file in the older versions so I could just require it and use it.  Since 0.9 this is now rolled up and internalized and no longer accessible.
> Expose LineWrapper class

- lib/security.js
It fixes https://github.com/foliojs/pdfkit/issues/1110 by adding `valueOf()` to the info-items accumulated in `generateFileID`.
This has no affect on the primitive items, but causes the Date object (`CreationDate`) to return a UNIX-Timestamp instead of the platform and timezone dependent date-string.
This change makes the output of `generateFileID` stable between environments.
**Checklist**:
One minor thing: Adding `info.CreationDate.getTime()` in line 11 seems redundant.
Should we remove that as well?
> Added `valueOf()` to info-items in `generateFileID`

- CHANGELOG.md
- lib/font/embedded.js
- tests/unit/font.spec.js
Adobe Illustrator fails to load fonts that have the `@` sign in FontName.
Example PDF created by PDFKit (snippet):
```
38 0 obj
<<
/Ascent 750
/CapHeight 720
/Descent -250
/Flags 4
/FontBBox [
-45
-236
1749
997
]
/FontFile2 43 0 R
/FontName /A@ZZZZ+MetaHeadlinePro
/ItalicAngle 0
/StemV 0
/Type /FontDescriptor
/XHeight 546
>>
endobj
```
And this is how the Adobe Illustrator error message looks like:
The problem is in `Embedded.embed()`. This function creates font name by translating numbers in the font id to letters. This works well for numbers 1-9, which get translated to `A-I`, but as soon as there is a 0 in the number, it gets translated to `@`.
Change `Embedded.embed()` to translate 0-9 to `A-J`.
- n/a Documentation -> **It's a bug fix**
> Fix "@" in FontName

- lib/mixins/markings.js
- tests/unit/markings.spec.js
Fix for https://github.com/foliojs/pdfkit/issues/1260
**Checklist**:
> Fix for PDF accessibility check.

- README.md
The apostrophe in "you're" disrupts the syntax highlighting on pdfkit.org.
Syntax highlighting on github is fine.
**Checklist**:
This change would fix the following issue:
> Fix syntax highlighting on pdfkit.org

- CHANGELOG.md
- docs/getting_started.md
- lib/mixins/pdfa.js
- lib/mixins/subsets.js
- tests/unit/pdfa2.spec.js
- tests/unit/pdfa3.spec.js
Feature
**Checklist**:
It seems like PDF/A-2 and PDF/A-3 are not very different from PDF/A-1 as far as the A and B subsets are concerned (level A conformance requires tagging which PDFKit supports already). With this change, we can let the generated PDF present itself as PDF/A-2 with either level A or B conformance, or, PDF/A-3 with either level A or B conformance.
Note that the user is still required to ensure all other aspects and requirements for the PDF/A subset are met, such as not embedding files in subset PDF/A-1 (embedded files is OK only from PDF/A-3) and using the correct `pdfVersion` e.g. `1.4` for PDF/A-1 and `1.7` for PDF/A-2 or PDF/A-3.
> Support for PDF/A-2 and PDF/A-3 subsets

- docs/getting_started.md
Docs update
**Checklist**:
The standard fonts that come in AFM format cannot be embedded for PDF/A support. Updated the docs to note that and suggested using `registerFont()` with ttf.
> Added note to docs regarding PDF/A not supporting the standard AFM fonts

- CHANGELOG.md
- package.json
- yarn.lock
**Bump crypto-js from 4.0.0 to 4.2.0 to fix CVE-2023-46233**
The error is raised after a `yarn audit`
**Checklist**:
> Bump crypto-js from 4.0.0 to 4.2.0 to fix CVE-2023-46233

- CHANGELOG.md
- docs/accessibility.md
- lib/mixins/pdfua.js
- lib/mixins/subsets.js
- tests/unit/pdfua.spec.js
Improves existing PDF/UA compliance by allowing users to use `subset: 'PDF/UA'` when creating the `PDFDocument` which will result PDF/UA to be added to the created PDF metadata.
**Checklist**:
Currently we're implementing PDF/UA compliance and are going through a checklist of requirements we must meet in order to generare valid PDF/UA PDFs.
One of the first requirements we haven't been able to meet is a missing PDF/UA identifier from the PDF's metadata.
With this change, the checks seems to pass (using [PAC 2021 - PDF Accessibility Checker](https://pdfua.foundation/en/pdf-accessibility-checker-pac/) for testing compliance).
> Add PDF/UA subset

- lib/image.js
- lib/mixins/attachments.js
As noted by #381, adding large base64-encoded images produces an error.  This happens because the file format ("image/png", "image/jpeg", etc.) is matched with the infamous `.*` pattern,  which matches the entire string (before backtracking).  This change makes it lazy. 
**Checklist**:
> Made regex quantifier lazy to resolve #381

- CHANGELOG.md
- lib/mixins/vector.js
- tests/unit/vector.spec.js
This makes the resulting PDF files smaller. It's cumbersome to filter out all commands that could result in identity transforms in code that's using PDFKit, so it makes sense to have the check in the transform() function.
**Checklist**:
This change is sponsored by [Higharc](https://higharc.com).
> Prevent adding identity transforms to the document

- CHANGELOG.md
- lib/mixins/acroform.js
- tests/unit/acroform.spec.js
This PR fixes #1495 (Acroforms - setting an option to false will still apply the flag).
**Checklist**:
> Fix Acroforms - setting an option to false will still apply the flag

- CHANGELOG.md
- lib/font/embedded.js
- tests/unit/font.spec.js
Bug fix of https://github.com/foliojs/pdfkit/issues/1498
**Checklist**:
> Generate ToUnicodeMap bfrange in multiple ranges (#1498)

- lib/mixins/acroform.js
Updated error text document.initForms() to document.initForm() as correct method name is initForm()
Typo fix in error text
**Checklist**:
> acroform error message update

- lib/mixins/attachments.js
- tests/unit/attachments.spec.js
The change fixes a bug in how file equality is checked which leads to bloated pdf sizes; in particular, the dates for when a file was modified or created are checked for reference equality rather than by comparing whether the date objects represent the same date.
**Checklist**:
> Bugfix: File Cache Equality Check Incorrectly Compares Dates

- docs/attachments.md
- lib/mixins/attachments.js
- tests/unit/attachments.spec.js
Fixes part of #1561 
I followed the contributing guide, but this did not work. All tests failed due to some jest config problem:
```
Jest encountered an unexpected token
Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
```
Is the contributing guide up-to-date?
> fix: pdf/a compliance of attachments

- lib/mixins/acroform.js
Bug fix.
**Description**
When a font is missing in the acroform fonts dict, it is not getting added to it since a condition issue.
A key is missing means its value equals `undefined`. So that, the strict comparison to `null` is incorrect.
```js
const wrong = undefined === null; // false
const correct = undefined == null; // true
```
**Checklist**:
> fix missing acroform font identification

- CHANGELOG.md
- lib/line_wrapper.js
- lib/utils.js
- tests/unit/line_wrapper.spec.js
Handle JS quirks with large decimal precision checks resulting from the calculations of next lines in the LineWrapper
**Checklist**:
Yes this is a very niche situation but it has caused many headaches for me when working with very precise measurements and/or weird font sizes
> Fix precision rounding issues in LineWrapper

- CHANGELOG.md
- docs/getting_started.md
- lib/mixins/fonts.js
- lib/page.js
- lib/utils.js
- tests/unit/document.spec.js
- tests/unit/font.spec.js
- tests/unit/utils.spec.js
- New Feature:
- Enable defining sizes using any units (defaulting to Points)
- This also allows us to define sizes based on the current font context i.e. em's
- The new public `sizeToPoint` method allows users to also interact with these sizes to generate the correct point sizes
- Examples provided in docs
**Checklist**:
> Add support for dynamic sizing

- lib/utils.js
- tests/unit/utils.spec.js
Fix error which occurs when `normalizeSides` is called with a non-object non-string/number e.g. a boolean.
**Checklist**:
> Fix side normalize when non-object

- CHANGELOG.md
- lib/document.js
- lib/page.js
- tests/unit/page.spec.js
When text overflows onto a new page and the page is created, any new pages it makes are defined using the default document page options rather than the current page.
This fixes that by forcing `continueOnNewPage` to inherit the current page options.
**Checklist**:
> Fix page cascade options when text overflows
