foliojs/pdfkit

docs/getting_started.coffee.md
lib/document.coffee

Allow automatic first page to be disabled (#65).

---

lib/image/png.coffee

fixes PNG image generation error: document is not defined

---

docs/getting_started.coffee.md
lib/document.coffee

Emit an event when a page is added

---

Makefile

Issue #454: JS not being generated for NPM

---

lib/object.coffee

You're welcome to pull my fix for the month meta data bug if this is how you would like to address it.

add 1 to javascript month for pdf month num

---

lib/image.coffee

This already works for fonts, so I applied the same technique so images can be loaded similarly.

Add support for ArrayBuffer-based images

---

README.md
docs/images.coffee.md

Added examples for https://github.com/devongovett/pdfkit/pull/250 and https://github.com/devongovett/pdfkit/pull/78

Added image example to README

---

docs/text.coffee.md

close #540 close #439 close #348

Docs update: widthOfString, heightOfString, list

---

lib/document.coffee
lib/mixins/text.coffee
lib/mixins/vector.coffee
lib/path.coffee

fix #562 fix #520 fix #409 fix #285

Pdf corruption with small numbers

---

docs/paper_sizes.coffee.md

I am not sure which branches should I target exactly so I'll open two requests one for master and the other for gh-pages. Hopefully, this will fix the bug since it is related to website.

Fixed #652 - Added page sizes docs page

---

lib/line_wrapper.coffee

- Fix #689 (the bug I created last year)
- Fix #345 (the original issue)

Fix linewrapper bug

---

lib/gradient.coffee

Detect color space from the first gradient stop

support CMYK gradients

---

lib/mixins/text.coffee

Add support for numbered and lettered lists to `doc.list()` via a new `listType` option which can  
have the following values: `'bullet'` (the default), `'numbered'` and `'lettered'`.
Usage:
```js
doc.list(["Item 1", "Item 2", "Item 3"], x, y, { listType: 'numbered' });`
```
Will generate the following list:
```
1. Item 1
2. Item 2
3. Item 3
```

Add support for numbered and lettered lists

---

README.md

Signed-off-by: Ry Jones <ry@linux.com>

Remove outdated Gratipay reference

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
package.json

This should help improve quality of issues and pull requests

Add contributing, issue and pull request templates

---

package.json
yarn.lock

Upgrade browserify dependency
Related to #923 (browser demo is fixed)
**Checklist**:

Upgrade to latest browserify

---

lib/font_factory.js

Refactor. This simplify usage in browser
call fontkit.openSync
Do not call fontkit.openSync
**Checklist**:

Do not call fontkit.openSync

---

CHANGELOG.md
lib/virtual-fs.js
rollup.config.js
tests/unit/virtual-fs.spec.js

Feature. Add a standalone / in memory virtual file system implementation in a separated file, to be used in browser
No virtual file system
No new behavior
**Checklist**:

Add standalone virtual file system implementation

---

tests/unit/annotations.spec.js

Test for link annotation (#957)

Add link annotation test

---

lib/mixins/annotations.js
lib/mixins/images.js
lib/mixins/text.js
lib/mixins/vector.js
lib/outline.js
lib/page.js
lib/reference.js

Added ES6 syntax for default values in all methods. (based on comment: https://github.com/foliojs/pdfkit/pull/947#discussion_r268427741 )
**Checklist**:

ES6 syntax for default values

---

docs/generate_website.js

Solves https://github.com/foliojs/pdfkit/issues/966. Details in https://github.com/foliojs/pdfkit/issues/966.
Requirements:
- ImageMagick https://imagemagick.org/

Cross-platform support for generate docs

---

CHANGELOG.md
lib/mixins/text.js
tests/unit/text.spec.js

Fixes #477 #877 #391
Hangs
**Checklist**:

Fix infinite loop when text is positioned after page right margin. Based on #986

---

.github/PULL_REQUEST_TEMPLATE.md

Simplify github PR template

---

CHANGELOG.md
rollup.config.js

Outputs clearer / smaller code
**Checklist**:

Do not emit interopDefault helper

---

CHANGELOG.md
package.json

Drop support for (uncommon) cid less fonts on standalone build (reduces standalone bundle size by 300kb)
**Checklist**:

Do not bundle iconv-lite on standalone build

---

docs/forms.md

Minor docs update.
**Checklist**:
It should be **document.font()** (as described everywhere in documentation) instead of **document.setFont()**.

Minor fix in Forms documentation

---

CONTRIBUTING.md

was going through steps in Contributing.md, find that one instruction was't working :)
so fixed wrong npm script in Contributing doc
**Checklist**:

contribution, fixed wrong npm script name in Contributing doc 🤓

---

lib/security.js

Access permissions are not applied to PDF if pdfVersion is "1.7ext3".

---

lib/virtual-fs.js
tests/unit/virtual-fs.spec.js

Pass 'encoding' param of VFS' readFileSync to 'toString'

---

docs/generate.js

https://github.com/foliojs/pdfkit/issues/991
https://github.com/foliojs/pdfkit/pull/1013
**Checklist**:

fix guide generate link

---

demo/browser.js

Small improvement in the live demo
**Checklist**:

fix(demo): debounces the preview to avoid window crash

---

lib/mixins/attachments.js

This PR is just a minor refactor, I was going through the code and saw an "optimization" of an avoidable 'if' statement.
The boolean expression in the condition is enough to check the equality of the objects.

Refactor on equality check function

---

docs/paper_sizes.md

Correct spelling of 'standard'.
**Checklist**:

Fix typo in paper_sizes.md

---

lib/metadata.js
lib/mixins/pdfa1.js

Lint Error Fix and PDF/A1 Test fix
**Checklist**:
This change fixes an unnecessary semicolon lint error.

Fixed lint's unnecessary semicolon error

---

examples/webpack/package.json

Update webpack example dependencies
**Checklist**:

Update webpack example dependencies

---

README.md

A correction to the README.md docs. The current [complete example](https://github.com/blikblum/pdfkit-webpack-example) for webpack is outdated. 
**Checklist**:

Update webpack complete example link

---

docs/getting_started.md

Fix doc about creation of pdf document

---

CHANGELOG.md
lib/table/utils.js
tests/unit/table.spec.js

Fixes https://github.com/foliojs/pdfkit/issues/1608
**Checklist**:

Fix table with null text

---

docs/css/index.css

Fix sidebar scrolling when the content bigger than container
**Checklist**:
Fixes #1575

docs: fix sidebar scrolling when the content bigger than container
